### ISSUE TITLE
Manage custom error message

### ISSUE THREAD

**Issue by camory** [TGOlson/o-validator#7]
It would be a nice to have the possibility to specify the error message for a given predicate. So the error message could be more accurate for the user.

**Comment by TGOlson** [comment]
@camory that's a great idea. I've been wanting to add that functionality for a while now, but I'm not sure the best way to do it. I really like how all the values in a schema are just simple predicates...

I guess the first solution I think of is:

``` js
V.validate({
  foo: {
    predicate: ...,
    onFailureMessage: function(value) {
      // return some error message here
    }
  }
});
```

But then we get into the game of supplying predicates OR special looking objects as schema values. What are your thoughts? Any other ideas about what would be useful?

**Comment by TGOlson** [comment]
Follow up - does `getErrors` help you at all here?

You can validate an object against a schema, and get back a list of errors, at which point you can easily construct your own error messages.

``` js
Validator.getErrors :: Schema -> Object -> [ErrorObjectWithMessage]

ErrorObjectWithMessage :: {property: String, errorCode: String, message: String}
```

**Comment by camory** [comment]
A field can have more than one predicate, like 'description' in your example. If more than predicates fails, there is no details about which predicate fails as there is one error message par by error code.
For example:

``` javascript

var V = require('o-validator');
var R = require('ramda');

var hasLengthGreaterThan = R.curry(function(n, x) {
    return R.propSatisfies(R.lt(n), 'length', x);
});

var function isPasswordStrongEnough(a) {
    return /[\W]/.test(a);
}

    var schema = {
    title       : V.required(R.is(String)),
    description : R.allPass([R.is(String), hasLengthGreaterThan(5), isPasswordStrongEnough]),
    isActive    : R.is(Boolean),
    tags        : R.is(Array)
};

V.getErrors(schema, {
    title       : 'Hi There',
    description : 'Yo',
    isActive    : true
});

//[ { property: 'description',
//    errorCode: 'VALUE',
//    message: 'Illegal value for parameter "description"' } ]
```

Here, the two predicates fail but we have only one error message.

Predicates are good but not enough to manage this kind of feature.
Did you take a look at [ramda-fantasy-validation](https://github.com/mrkm4ntr/ramda-fantasy-validation) ?

**Comment by TGOlson** [comment]
@camory - sorry for the late follow up here. What your saying makes a lot of sense, but I don't see a simple way of supporting that feature without fundamentally altering the library. `ramda-fantasy-validation` is a really good example of a library that's very extensible, which is great. The goal of this library is to be very quick and easy to use, without special syntax or validation functions. If someone needed finer grain control of error messages, other libraries might make more sense.
